### ISSUE TITLE
cellPLATO usage with csv or npz files

### ISSUE THREAD

**Issue by Ciro1990** [Michael-shannon/cellplato#1]
Hi Michael, 

I have seen your paper on JCS, congratulations. The tool looks really interesting, I would love to test it on my data. However, I do not have .h5 files for the segmentation/tracking, but an array of segmentation labels (in an npz file) or as coordinates in a csv file (x,y and ID). Is it possible to use these files on cellPLATO?

Thanks a lot!
Ciro

**Comment by Michael-shannon** [comment]
Hey Ciro

Sorry for the late response! I moved to a new position and was setting up here.

Yes, its possible - probably the easiest way to help you would be for you to send me a couple of example data files, so I can make sure everything works simply.

Best,
Michael

**Comment by Ciro1990** [comment]
Hi Michael, 

Thanks for the reply and congrats for the new position! 

Sure, I can give you a couple of examples. Are the npz files enough or do you need the images too? 

Thanks!
Ciro

**Comment by Michael-shannon** [comment]
Mind sending me the csvs and npzs?

Best,
Michael

**Comment by Ciro1990** [comment]
Sure, I will email them to you :)

**Comment by Ciro1990** [comment]
I could not email them to u, so I am trying to upload them here: 
[Example_Ciro.zip](https://github.com/user-attachments/files/16438147/Example_Ciro.zip)

**Comment by Michael-shannon** [comment]
Hi Ciro

I will have a look at this this week, thanks!

M

**Comment by Michael-shannon** [comment]
Hi Ciro

If you pull the latest version, you should be able to handle your csv files now, just change the input_format and track_filename in the config.py to 'csv' and '.csv' respectively.

Let me know if it works!

Best,
M
